_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.5
            "8":
                - 2
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 32
embedding_dim:
    value: 300
hidden_dim:
    value: 300
learning_rate:
    value: 0.001
num_epochs:
    value: 50
num_topics:
    value: 10
